### ISSUE TITLE
mix docs results in ArgumentError

### ISSUE THREAD

**Issue by jsncmgs1** [jsncmgs1/spotify_ex#55]
```
➜  spotify_ex git:(main) mix docs
** (ArgumentError) expected a keyword list, but an entry in the list is not a two-element tuple with an atom as its first element, got: {{:message, 1}, [{:type, 35, :fun, [{:type, 35, :product, [{:user_type, 35, :t, []}]}, {:remote_type, 35, [{:atom, 0, String}, {:atom, 0, :t}, []]}]}]}
    (elixir 1.12.3) lib/keyword.ex:475: Keyword.keys/1
    (ex_doc 0.19.3) lib/ex_doc/retriever.ex:379: anonymous fn/2 in ExDoc.Retriever.get_impls/1
    (elixir 1.12.3) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ex_doc 0.19.3) lib/ex_doc/retriever.ex:378: ExDoc.Retriever.get_impls/1
    (ex_doc 0.19.3) lib/ex_doc/retriever.ex:161: ExDoc.Retriever.get_module_data/2
    (ex_doc 0.19.3) lib/ex_doc/retriever.ex:112: ExDoc.Retriever.generate_node/3
    (elixir 1.12.3) lib/enum.ex:3900: Enum.flat_map_list/2
    (elixir 1.12.3) lib/enum.ex:3901: Enum.flat_map_list/2
```

**Comment by avinayak** [comment]
It looks like the issue is fixable by bumping ex_doc version to 0.28.4

https://github.com/jsncmgs1/spotify_ex/pull/56
